name = "lyrics-app"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
account_id = "9a0d3ae785f5f07eb410e63ec29712ec"

[site]
bucket = ".output/public"
