name = "lyrics-app"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[vars]
BASE_URL = 'https://musikus.gutikus.schlau.bi'
WS_URL = 'wss://musikus.gutikus.schlau.bi'