name = "lyrics-app"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"
account_id = "9a0d3ae785f5f07eb410e63ec29712ec "

[vars]
BASE_URL = 'https://musikus.gutikus.schlau.bi'
WS_URL = 'wss://musikus.gutikus.schlau.bi'