name: CI

on:
    push:
        branches:
            - master
env:
  BASE_URL: musikus.gutikus.schlau.bi

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                cache: 'pnpm'
            - run: pnpm i --shamefully-hoist
            - run: pnpm run build
              env:
                NITRO_PRESET: cloudflare
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}                