name: CI

on:
    push:
        branches:
            - master
env:
  BASE_URL: musikus.gutikus.schlau.bi

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                cache: 'pnpm'
            - run: pnpm i --shamefully-hoist
            - run: pnpm run build
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              env:
                # https://github.com/cloudflare/workers-sdk/issues/6466#issuecomment-2288798843
                CLOUDFLARE_ACCOUNT_ID: 9a0d3ae785f5f07eb410e63ec29712ec
              with:
                apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
                command: pages deploy